### ISSUE TITLE
KarafManipulatorFactory does not work with versions containing non-numeric elements

### ISSUE THREAD

**Issue by lichtin** [ops4j/org.ops4j.pax.exam2#1120]
java.lang.IllegalArgumentException: invalid version "8.1.SNAPSHOT": non-numeric "SNAPSHOT"
	at org.osgi.framework.Version.parseInt(Version.java:169)
	at org.osgi.framework.Version.<init>(Version.java:134)
	at org.ops4j.pax.exam.karaf.container.internal.adaptions.KarafManipulatorFactory.createManipulator(KarafManipulatorFactory.java:39)
	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.createVersionAdapter(KarafTestContainer.java:256)
	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.start(KarafTestContainer.java:161)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)
Caused by: java.lang.NumberFormatException: For input string: "SNAPSHOT"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.osgi.framework.Version.parseInt(Version.java:167)
	... 15 more

Packaging a custom Karaf version, it should be possible to run Pax-Exam tests with a SNAPSHOT version, e.g. 8.1-SNAPSHOT.

**Comment by oliverlietz** [comment]
8.1-SNAPSHOT is not a valid [OSGi Version](https://docs.osgi.org/whitepaper/semantic-versioning/040-semantic-versions.html).

> Version identifiers have four components.
> 
> 1. Major version. A non-negative integer.
> 2. Minor version. A non-negative integer.
> 3. Micro version. A non-negative integer.
> 4. Qualifier. A text string. See Version(String) for the format of the qualifier string.

**Comment by lichtin** [comment]
Well, we are talking here about a container, not a Bundle version (which is a valid OSGi version).
Any valid Maven version should work.

**Comment by oliverlietz** [comment]
Sorry if you did not get my point. OSGi and Karaf (as well as lots of other projects) use [Semantic Versioning](https://semver.org).
Add a Micro/Patch version to fix your issue.

**Comment by lichtin** [comment]
I understand your point, but I don't see how it is relevant in this code section. 
Afaics, there's no reason KarafManipulatorFactory parses this version as an OSGi version.
It's using org.osgi.framework.Version merely as a convenience.
The packaged Karaf is not itself a bundle, but a zip/tgz and requiring this to carry a valid OSGi version seems unnecessary.

**Comment by oliverlietz** [comment]
The version check in `KarafManipulatorFactory` is quite lax but does its job. The version of your distribution is not relevant here, it's the [**Karaf version**](https://central.sonatype.com/artifact/org.apache.karaf/karaf/versions) which gets checked. Please read the sources and comments.
