### ISSUE TITLE
Unable to build the Forked Test Container module and launch Forked Container under Windows [PAXEXAM-360]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#493]
**[Vincent Vallet](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:7bd78785-1278-4a79-bd63-a10f58456735)** created **[PAXEXAM-360](https://ops4j1.jira.com/browse/PAXEXAM-360)** 

How to reproduce?

=&gt; try to build the Forked Test Container module: ForkedFrameworkFactoryTest fails

or

=&gt; try to launch a Pax exam test using the Forked Test Container

Class loading issue:

java.lang.NoClassDefFoundError: org/ops4j/pax/swissbox/framework/RemoteFrameworkImpl<br /> Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.swissbox.framework.RemoteFrameworkImpl<br /> at java.net.URLClassLoader$1.run(URLClassLoader.java:202)<br /> at java.security.AccessController.doPrivileged(Native Method)<br /> at java.net.URLClassLoader.findClass(URLClassLoader.java:190)<br /> at java.lang.ClassLoader.loadClass(ClassLoader.java:306)<br /> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)<br /> at java.lang.ClassLoader.loadClass(ClassLoader.java:247)<br /> Could not find the main class: org.ops4j.pax.swissbox.framework.RemoteFrameworkImpl. Program will exit.<br /> Exception in thread "main"

I've fixed the problem modifying the way the classpath is built in ForkedFrameworkFactory.buildClassPath():<br /> I use url.toURI().getPath() instead of url.toString():

frameworkFactory.getClass().getProtectionDomain().getCodeSource().getLocation().toURI().getPath();<br /> instead of<br /> frameworkFactory.getClass().getProtectionDomain().getCodeSource().getLocation().toString();

---

**Affects:** 2.4.0.RC1
**Fixed in:** 2.4.0
Votes: 2, Watches: 0

**Comment by vassilz** [comment]
Hi,

Still happening in pax-exam 5.0.0-SNAPSHOT on Windows:

Running org.ops4j.pax.exam.forked.ReferenceJarTest

361248 [main] INFO org.ops4j.pax.exam.junit.DriverExtension - creating PaxExam runner for class org.ops4j.pax.exam.forked.ReferenceJarTest
361259 [main] INFO org.ops4j.pax.exam.ExamJavaRunner - ExamJavaRunner completed successfully
361259 [main] INFO org.ops4j.pax.exam.forked.ForkedFrameworkFactory - Connecting to host: 127.0.0.1 port: 21007
Error: Could not find or load main class org.ops4j.pax.swissbox.framework.RemoteFrameworkImpl
Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.swissbox.framework.RemoteFrameworkImpl
421262 [main] INFO org.ops4j.pax.exam.spi.reactors.ReactorManager - suite finished
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 59.972 sec <<< FAILURE! - in org.ops4j.pax.exam.forked.ReferenceJarTest
getHelloService(org.ops4j.pax.exam.forked.ReferenceJarTest)  Time elapsed: 0.003 sec  <<< ERROR!
org.ops4j.pax.exam.TestContainerException: cannot find remote framework in RMI registry
	at org.ops4j.pax.exam.forked.ForkedFrameworkFactory.findRemoteFramework(ForkedFrameworkFactory.java:244)
	at org.ops4j.pax.exam.forked.ForkedFrameworkFactory.fork(ForkedFrameworkFactory.java:131)
	at org.ops4j.pax.exam.forked.ForkedTestContainer.start(ForkedTestContainer.java:155)
	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.runTest(AllConfinedStagedReactor.java:89)
	at org.ops4j.pax.exam.junit.DriverExtension.delegateMethodBlock(DriverExtension.java:181)
	at org.ops4j.pax.exam.junit.ExtensibleRunner.runChild(ExtensibleRunner.java:107)
	at org.ops4j.pax.exam.junit.ExtensibleRunner.runChild(ExtensibleRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.ops4j.pax.exam.junit.ExtensibleRunner$1.evaluate(ExtensibleRunner.java:61)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:78)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.rmi.NotBoundException: ExamRemoteFramework-57056e68-4e06-427e-b52a-8741961d691b
	at sun.rmi.registry.RegistryImpl.lookup(RegistryImpl.java:227)
	at sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:115)
	at sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:472)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:299)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:375)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:119)
	at org.ops4j.pax.exam.forked.ForkedFrameworkFactory.findRemoteFramework(ForkedFrameworkFactory.java:236)
	at org.ops4j.pax.exam.forked.ForkedFrameworkFactory.fork(ForkedFrameworkFactory.java:131)
	at org.ops4j.pax.exam.forked.ForkedTestContainer.start(ForkedTestContainer.java:155)
	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.runTest(AllConfinedStagedReactor.java:89)
	at org.ops4j.pax.exam.junit.DriverExtension.delegateMethodBlock(DriverExtension.java:181)
	at org.ops4j.pax.exam.junit.ExtensibleRunner.runChild(ExtensibleRunner.java:107)
	at org.ops4j.pax.exam.junit.ExtensibleRunner.runChild(ExtensibleRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.ops4j.pax.exam.junit.ExtensibleRunner$1.evaluate(ExtensibleRunner.java:61)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:78)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
